# This file was generated by GoReleaser. DO NOT EDIT.
cask "gemctl" do
  name "gemctl"
  desc "A powerful Go CLI for managing Google Gemini Enterprise resources"
  homepage "https://github.com/vb140772/gemctl-go"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gemctl"

  on_macos do
    on_intel do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_darwin_amd64.tar.gz"
      sha256 "270784e5ff9fcacb1bb47773d8d8950d29a4afe7a2c1f94f2ee25d7e920cff47"
    end
    on_arm do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_darwin_arm64.tar.gz"
      sha256 "a2c886edca410a12c7cac66b13a60dba36da329443e84b0359a9c562d5c49442"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_linux_amd64.tar.gz"
      sha256 "ad4c963f8daf7cf67cdcb4cc84c1b8dc12133782e0473aae403a779628968603"
    end
    on_arm do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_linux_arm64.tar.gz"
      sha256 "e2238afe94ea4094754751798820b97d562e502a64947bb77effe142d9a8a66c"
    end
  end

  # No zap stanza required
end
