# This file was generated by GoReleaser. DO NOT EDIT.
cask "gemctl" do
  name "gemctl"
  desc "A powerful Go CLI for managing Google Gemini Enterprise resources"
  homepage "https://github.com/vb140772/gemctl-go"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gemctl"

  on_macos do
    on_intel do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_darwin_amd64.tar.gz"
      sha256 "ed923183385888af640b2551348a225f177198f223ce7fb07d0b1db3fe764025"
    end
    on_arm do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_darwin_arm64.tar.gz"
      sha256 "df3b8e1fae6ca2863e0246e97ff0cbc8aeccb99fcafc260d03d9538e40f1216f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_linux_amd64.tar.gz"
      sha256 "59da844874cd2dbdac8617827868ec8c426c93ca0a7162953ebeb2aa1d37141b"
    end
    on_arm do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_linux_arm64.tar.gz"
      sha256 "3cac3e226c5ab0cc63d71cf3b8db973b12a6ab8b581815449cec2a4f3e8fc34d"
    end
  end

  # No zap stanza required
end
