# This file was generated by GoReleaser. DO NOT EDIT.
cask "gemctl" do
  name "gemctl"
  desc "A powerful Go CLI for managing Google Gemini Enterprise resources"
  homepage "https://github.com/vb140772/gemctl-go"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gemctl"

  on_macos do
    on_intel do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_darwin_amd64.tar.gz"
      sha256 "94b105cf933243a4e6f271bd149811b33acadbd8d2ae48405f62acc656778b79"
    end
    on_arm do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_darwin_arm64.tar.gz"
      sha256 "46e90f7bde14e6f387fbdd6a784fa879ef583e8e50cff75d00e273a66fb872ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_linux_amd64.tar.gz"
      sha256 "9d92d0af4ba21b231e4f3be76de9b4eb5cae8fc33c0e6841747002d4a393a822"
    end
    on_arm do
      url "https://github.com/vb140772/gemctl-go/releases/download/v#{version}/gemctl_#{version}_linux_arm64.tar.gz"
      sha256 "9452ea46476f862246c4dbc532f91c4e7159edc2d341fa34f1191cebec37590c"
    end
  end

  # No zap stanza required
end
